services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        #bind:
            #$projectDir: '%kernel.project_dir%'

    _instanceof:
        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            calls:
                - [ setContainer, [ '@service_container' ] ]


    Markocupic\ContaoContentApi\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources,Model,Api}

    markocupic_contao_content_api.backend.app:
        class: Markocupic\ContaoContentApi\Backend\TlApp

    markocupic_contao_content_api.controller.content_api:
        class: Markocupic\ContaoContentApi\Controller\ContentApiController
        calls:
            - [setContainer, ['@service_container']]

    markocupic_contao_content_api.user.contao.frontend:
        class: Markocupic\ContaoContentApi\User\Contao\ContaoFrontenduser

    markocupic_contao_content_api.manager.resource:
        class: Markocupic\ContaoContentApi\Manager\ApiResourceManager

    markocupic_contao_content_api.resource.contao_frontend_module:
        class: Markocupic\ContaoContentApi\Api\ApiFrontendModule
        tags:
            - { name: markocupic_contao_content_api.resource, alias: contao_frontend_module }

    markocupic_contao_content_api.resource.contao_logged_in_frontend_user:
        class: Markocupic\ContaoContentApi\Api\ApiLoggedInFrontendUser
        tags:
            - { name: markocupic_contao_content_api.resource, alias: contao_logged_in_frontend_user }
