services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $contaoContentApiConfig: '%markocupic_contao_content_api%'

    Markocupic\ContaoContentApi\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources,Model,Api}

    Markocupic\ContaoContentApi\Api\ApiFrontendModule:
        public: false
        tags:
            - { name: markocupic_contao_content_api.resource, alias: contao_frontend_module }

    markocupic_contao_content_api.resource.contao_content_element:
        class: Markocupic\ContaoContentApi\Api\ApiContentElement
        tags:
            - { name: markocupic_contao_content_api.resource, alias: contao_content_element }

    markocupic_contao_content_api.resource.contao_logged_in_frontend_user:
        class: Markocupic\ContaoContentApi\Api\ApiLoggedInFrontendUser
        tags:
            - { name: markocupic_contao_content_api.resource, alias: contao_logged_in_frontend_user }

    markocupic_contao_content_api.resource.author:
        class: Markocupic\ContaoContentApi\Api\ApiContentElement
        tags:
            - { name: markocupic_contao_content_api.resource, alias: author }