services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        #bind:
            #$projectDir: '%kernel.project_dir%'

    Markocupic\ContaoContentApi\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources}

