services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        #bind:
            #$projectDir: '%kernel.project_dir%'

    Markocupic\ContaoContentApi\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources,Model,Api}

    markocupic.api.manager.resource:
        class: Markocupic\ContaoContentApi\Manager\ApiResourceManager

    markocupic.api.resource.contao_frontend_module:
        class: Markocupic\ContaoContentApi\Api\ApiFrontendModule
        tags:
            - { name: markocupic.api.resource, alias: contao_frontend_module }
